[package]
name = "q_compress"
version = "0.2.3"
edition = "2018"

authors = ["mwlon <m.w.loncaric@gmail.com>"]
categories = ["compression", "encoding"]
description = "Good data compression for numerical sequences"
include = ["src/**/*.rs", "Cargo.toml"]
keywords = ["compression", "numerical", "quantile"]
license = "Apache-2.0"
repository = "https://github.com/mwlon/quantile-compression"

[dependencies]
