[package]
name = "cpcodec"
version = "0.0.0"
edition = "2021"

[lib]
name = "cpcodec"
crate-type = ["dylib"]

[dependencies]
half = { version = "2.4.1", features = ["std"] }
libc = "0.2.132"
pco = { version = "0.3.0", path = "../pco" }
